### ISSUE TITLE
文字纠错

### ISSUE THREAD

**Issue by duzit** [lxchuan12/blog#29]
<img width="548" alt="image" src="https://user-images.githubusercontent.com/41765533/158038972-4c3dabde-6602-4f29-ab3b-9a0e4b333696.png">

- [锚点](https://lxchuan12.gitee.io/js-object-api/#object-defineproperty-obj-prop-descriptor-es5)

**Comment by lxchuan12** [comment]
哇，感谢指出，有空修正下~
